package SiteAppraisal;
//Generated by Selenium IDE
import org.junit.Test;
import org.junit.Before;
import org.junit.After;
import static org.junit.Assert.*;
import static org.hamcrest.CoreMatchers.is;
import static org.hamcrest.core.IsNot.not;
import org.openqa.selenium.By;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.firefox.FirefoxDriver;
import org.openqa.selenium.chrome.ChromeDriver;
import org.openqa.selenium.remote.RemoteWebDriver;
import org.openqa.selenium.remote.DesiredCapabilities;
import org.openqa.selenium.Dimension;
import org.openqa.selenium.WebElement;
import org.openqa.selenium.interactions.Actions;
import org.openqa.selenium.support.ui.ExpectedConditions;
import org.openqa.selenium.support.ui.WebDriverWait;

import io.github.bonigarcia.wdm.WebDriverManager;

import org.openqa.selenium.JavascriptExecutor;
import org.openqa.selenium.Alert;
import org.openqa.selenium.Keys;
import java.util.*;
import java.net.MalformedURLException;
import java.net.URL;
public class SiteappraisalfactorysideTest {
	
public static WebDriver driver;
private Map<String, Object> vars;
JavascriptExecutor js; 

public static void  main(String[]args) throws InterruptedException {
	WebDriverManager.chromedriver().setup();
	driver=new ChromeDriver();
	 driver.manage().window().maximize();
 driver.get("TYPE URL HERE");//FACTORY SIDE LOGIN URL
 Thread.sleep(2000);
 driver.findElement(By.name("username")).click();
 driver.findElement(By.id("Password")).sendKeys("Sanotax@123");
 driver.findElement(By.name("username")).sendKeys("accounts@sancepharma.com");
 driver.findElement(By.id("id")).click();
 Thread.sleep(8000);//for entering captcha
 //driver.findElement(By.id("id")).sendKeys("79492");
 driver.findElement(By.id("id")).sendKeys(Keys.ENTER);
 driver.findElement(By.cssSelector("td:nth-child(2) > div img")).click();
 driver.findElement(By.linkText("SANCE LABORATORIES PVT. LTD.")).click();
 driver.findElement(By.cssSelector("td:nth-child(7) img")).click();
 driver.findElement(By.cssSelector("a:nth-child(4) > .text-center")).click();
 driver.findElement(By.cssSelector(".accordion:nth-child(1) label")).click();
 driver.findElement(By.id("nameAndAddress")).click();
 driver.findElement(By.id("nameAndAddress")).sendKeys("jabir ep\\ntrivandrum/peroorkada");
 driver.findElement(By.id("revenueDetails")).sendKeys("tax is paid for this land");
 driver.findElement(By.id("whetherTheSiteIsClassifiedatus")).sendKeys("yes, the site is a part of amazon rain forest");
 driver.findElement(By.id("whetherTheProposedSiteAttracts")).click();
 driver.findElement(By.id("whetherTheProposedSiteAttracts")).sendKeys("wild population thick area");
 driver.findElement(By.id("localAuthorityUnder")).click();
 driver.findElement(By.id("localAuthorityUnder")).sendKeys("under farmer james. actually he is a latex farmer.");
 driver.findElement(By.id("sitePlanWithClearIdentification")).click();
 driver.findElement(By.id("sitePlanWithClearIdentification")).sendKeys("1 hectre");
 driver.findElement(By.id("historicalMonument")).click();
 driver.findElement(By.id("historicalMonument")).sendKeys("yeah, some historical monuments exists here.");
 driver.findElement(By.id("nameOfNeighbouringManufacturingUnits")).click();
 driver.findElement(By.id("nameOfNeighbouringManufacturingUnits")).sendKeys("A school is situated near the boundary of that forest. Also , some wild animals are living there.");
 driver.findElement(By.id("waterSources")).click();
 driver.findElement(By.id("waterSources")).sendKeys("streams are flowing through the forest.");
 driver.findElement(By.id("nearestHospitals")).sendKeys("civil defence station is situated near the forest. forest department building also there.");
 driver.findElement(By.id("highTensionElectricalTransmissionLine")).click();
 driver.findElement(By.id("highTensionElectricalTransmissionLine")).sendKeys("pipe line for water is going through the forest to near school and hospital for thier purpose.");
 driver.findElement(By.id("detailsOfSoilConditions")).click();
 driver.findElement(By.id("detailsOfSoilConditions")).click();
 driver.findElement(By.id("detailsOfSoilConditions")).sendKeys("soil is very good aluvial soil.");
 driver.findElement(By.id("contourMapOfTheAreaShowingNearby")).click();
 driver.findElement(By.id("contourMapOfTheAreaShowingNearby")).sendKeys("no hill rocks rich area.");
 driver.findElement(By.id("plotPlanOfTheFactoryShowingTheEntry")).click();
 driver.findElement(By.id("plotPlanOfTheFactoryShowingTheEntry")).sendKeys("entry points and exit points are there.");
 Thread.sleep(5000);//for waiting after entering details

 driver.findElement(By.cssSelector(".accordion:nth-child(1) .btn")).click();
 //assertThat(driver.switchTo().alert().getText(), is("Saved successfully"));
 Thread.sleep(2000);

 driver.findElement(By.id("estimateAmountEnter")).click();
 driver.findElement(By.id("estimateAmountEnter")).sendKeys("10000000");
 driver.findElement(By.id("payNowButton")).click();
 //assertThat(driver.switchTo().alert().getText(), is("Proceed to payment?"));
 driver.switchTo().alert().accept();
 Thread.sleep(2000);

 driver.findElement(By.id("attachmentType")).click();
 {
   WebElement dropdown = driver.findElement(By.id("attachmentType"));
   dropdown.findElement(By.xpath("//option[. = 'Site Plan']")).click();
 }
 driver.findElement(By.cssSelector("option:nth-child(2)")).click();
 driver.findElement(By.id("attach")).click();
 driver.findElement(By.id("attach")).sendKeys("C:\\fakepath\\fee receipt.pdf");
 driver.findElement(By.cssSelector(".btn-success")).click();
 //assertThat(driver.switchTo().alert().getText(), is("Document Uploaded Successfully"));
 driver.findElement(By.id("attachmentType")).click();
 {
   WebElement dropdown = driver.findElement(By.id("attachmentType"));
   dropdown.findElement(By.xpath("//option[. = 'Environment Impact Analysis Report']")).click();
 }
 driver.findElement(By.cssSelector("option:nth-child(3)")).click();
 driver.findElement(By.id("attach")).click();
 driver.findElement(By.id("attach")).sendKeys("C:\\fakepath\\fee receipt.pdf");
 driver.findElement(By.cssSelector(".btn-success")).click();
 //assertThat(driver.switchTo().alert().getText(), is("Document Uploaded Successfully"));
 driver.findElement(By.id("attachmentType")).click();
 {
   WebElement dropdown = driver.findElement(By.id("attachmentType"));
   dropdown.findElement(By.xpath("//option[. = 'Quantitative Risk Analysis Report']")).click();
 }
 driver.findElement(By.cssSelector("option:nth-child(4)")).click();
 driver.findElement(By.id("attach")).click();
 driver.findElement(By.id("attach")).sendKeys("C:\\fakepath\\Lesson Plan1.pdf");
 driver.findElement(By.cssSelector(".btn-success")).click();
 assertThat(driver.switchTo().alert().getText(), is("Document Uploaded Successfully"));
 driver.findElement(By.id("attachmentType")).click();
 {
   WebElement dropdown = driver.findElement(By.id("attachmentType"));
   dropdown.findElement(By.xpath("//option[. = 'HAZOP Study']")).click();
 }
 driver.findElement(By.cssSelector("option:nth-child(5)")).click();
 driver.findElement(By.id("attach")).click();
 driver.findElement(By.id("attach")).sendKeys("C:\\fakepath\\Lesson Plan1.pdf");
 driver.findElement(By.cssSelector(".btn-success")).click();
 //assertThat(driver.switchTo().alert().getText(), is("Document Uploaded Successfully"));
 driver.findElement(By.id("attachmentType")).click();
 {
   WebElement dropdown = driver.findElement(By.id("attachmentType"));
   dropdown.findElement(By.xpath("//option[. = 'Onsite Emergency Plan']")).click();
 }
 driver.findElement(By.cssSelector("option:nth-child(6)")).click();
 driver.findElement(By.id("attach")).click();
 driver.findElement(By.id("attach")).sendKeys("C:\\fakepath\\Lesson Plan1.pdf");
 driver.findElement(By.cssSelector(".col-md-5:nth-child(2) > .md-form")).click();
 driver.findElement(By.cssSelector(".btn-success")).click();
 //assertThat(driver.switchTo().alert().getText(), is("Document Uploaded Successfully"));
 driver.findElement(By.id("attachmentType")).click();
 {
   WebElement dropdown = driver.findElement(By.id("attachmentType"));
   dropdown.findElement(By.xpath("//option[. = 'Other Documents']")).click();
 }
 driver.findElement(By.cssSelector("option:nth-child(7)")).click();
 driver.findElement(By.id("attach")).click();
 driver.findElement(By.id("attach")).sendKeys("C:\\fakepath\\Lesson Plan1.pdf");
 driver.findElement(By.cssSelector(".btn-success")).click();
 //assertThat(driver.switchTo().alert().getText(), is("Document Uploaded Successfully"));
 //js.executeScript("window.scrollTo(0,532)");
 driver.findElement(By.cssSelector(".col-sm-12:nth-child(8) > .btn-primary")).click();
 //assertThat(driver.switchTo().alert().getText(), is("Saved successfully"));
 driver.findElement(By.id("submitSiteAppraisal")).click();
 //assertThat(driver.switchTo().alert().getText(), is("Submit this record?"));
 driver.switchTo().alert().accept();
 //assertThat(driver.switchTo().alert().getText(), is("Application Submitted !!!"));
 driver.findElement(By.xpath("//tr[@id=\'2\']/td[5]/u/b/span/i")).click();
 driver.findElement(By.id("attachmentModal")).click();
 driver.findElement(By.xpath("//tr[@id=\'2\']/td[6]/span/i")).click();
 driver.findElement(By.id("trackingModal")).click();
}
}
